import React from "react";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Name Placeholder</title>
        <meta
          content='Generated by @rainbow-me/create-rainbowkit'
          name='description'
        />
        <link href='/favicon.ico' rel='icon' />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <h1 className={styles.title}>
          Stake to defeat the Ethereal Boss and try to win the jackpot!
        </h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
